name: gisutils
channels:
- conda-forge
- defaults
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- numpy
- scipy
- xarray
- pandas
- geopandas
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- pyproj
- pyshp
