name: gisutils_ci
channels:
- conda-forge
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- numpy
- scipy
- xarray
- pandas
- geopandas
- gdal
- fiona
- rasterio
- rasterstats
- shapely
- pyproj
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx>7
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
