name: test
channels:
- conda-forge
- defaults
dependencies:
- python
- matplotlib
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- pyproj>=2.0
- pyshp
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- sphinx-copybutton
- sphinx_rtd_theme
