# Based on github template: https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Tests

on:
  schedule:
    - cron: '0 9 * * 1' # run every Monday at 9 AM UTC (3 am PST)
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.10', '3.9']

    steps:
    - uses: actions/checkout@v2
      #with:
      #  fetch-depth: 50
    # Setup conda env
    - name: Install Conda environment using micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ci/requirements.yml
        environment-name: gisutils_ci
        cache-downloads: true
        cache-env: true
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Install gis-utils and ipykernel
      shell: bash -l {0}
      run: |
        pip install -e .
        python -m ipykernel install --user --name gisutils_ci --display-name "gisutils_ci"
    - name: Conda list
      shell: bash -l {0}
      run: conda list
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests and upload coverage
      shell: bash -l {0}
      run: |
        coverage run -m pytest -v --durations=20
        coverage report -m
        codecov